# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lgUvYZfsGGGkRV61iBRfmI8cpSDaTrWk
"""

first = int(input("Informe o primeiro número "))

second = int(input("Informe o segundo número "))

def somar(n1, n2):
  soma = n1 + n2

  if soma > 15:
    return f"Resultado da soma é {soma}"

print(somar(first, second))

number = int(input("Informe um número "))
result = ""

if number < 0:
  result = "Negativo"
elif number > 0:
  result = "Positivo"
else:
  result = "Neutro"

print(result)

age = int(input("Informe sua idade "))
result = "Menor de idade"

if age >= 18:
  result = "Maior de idade"

print(result)

temperature = 100
result = "Quente"

if temperature < 20:
  result = "Frio"
elif temperature >= 20 and temperature < 25:
  result = "Agradavel"

print(result)

n1 = int(input("Informe o primeiro número "))
n2 = int(input("Informe o segundo número "))
result = "Diferentes"

if n1 == n2:
  result = "Iguais"

print(result)

password = int(input("Informe sua senha "))
valid_password = 1234
result = "ACESSO PERMITIDO"

if password != valid_password:
  result = "ACESSO NEGADO"

print(result)

nota1 = int(input("Informe a nota da sua primeira prova "))
nota2 = int(input("Informe a nota da sua segunda prova "))
media = (nota1 + nota2) / 2
result = "Reprovado"

if media >= 7:
  result = "Aprovado"
elif media >= 5 < 7:
  result = "Exame"

print(result)

santos = 0
curintia = 11
result = f"Curintia aplica uma goleada de {curintia} X {santos} no menor de SP"

if curintia < santos:
  result = f"Santos aplica uma goleada de {curintia} X {santos} no maior de SP"
elif curintia == santos:
  result = "Deu empate"

print(result)

period = str(input("Qual seu periodo? Digite M para matutino ou V- para Vespertino ou N para Noturno ")).lower()
result = "Valor Inválido!"

if period == "m":
  result = "Bom dia!"
elif period == "v":
  result = "Boa tarde!"
elif period == "n":
  result = "Boa noite!"

print(result)

age = int(input("Informe sua idade "))
result = "Idoso"

if age <= 11:
  result = "Criança"
elif age >= 12 and age <= 18:
  result = "Adolescente"
elif age >= 19 and age < 25 :
  result = "Jovem"
elif age >= 25 and age  <= 40:
  result = "Adulto"
elif age >= 41 and age  <= 60:
  result = "Meia Idade"

print(result)

salario = float(input("Qual seu salario? "))
originalSalario = salario
porcent = 0
porcent_1 = 0
aumento = 0

if salario <= 280:
  salario = salario * 1.2
elif salario > 280 and salario <= 700:
  porcent = 0.15
  porcent_1 = 1 + porcent
  aumento = salario - (salario * porcent_1)
  salario = salario * porcent_1
elif salario > 700 and salario <= 1500:
  porcent = 0.10
  porcent_1 = 1 + porcent
  aumento = (salario * porcent_1) - salario
  salario = salario * porcent_1
else:
  porcent = 0.05
  porcent_1 = 1 + porcent
  aumento = salario - (salario * porcent_1)
  salario = salario * porcent_1


print(f"Salario antigo {originalSalario}")
print(f"Percentual {porcent}")
print(f"Aumento de {aumento}")
print(f"Salario novo {salario}")

dia = int(input("Qual o dia da semana? "))
domingo = [1, 8, 15, 22, 29]
segunda = [2, 9, 16, 23, 30]
terca = [3, 10, 17, 24]
quarta = [4, 11, 18, 25]
quinta = [5, 12, 19, 26]
sexta = [6, 13, 20, 27]
sabado = [7, 14, 21, 28]

result = "Valor invalido"

if domingo.count(dia) > 0:
  result = "Domingo"
elif segunda.count(dia) > 0:
  result = "Segunda"
elif terca.count(dia) > 0:
  result = "Terça"
elif quarta.count(dia) > 0:
  result = "Quarta"
elif quinta.count(dia) > 0:
  result = "Quinta"
elif sexta.count(dia) > 0:
  result = "Sexta"
elif sabado.count(dia) > 0:
  result = "Sabado"

print(result)

one = str(input("Telefonou para a vítima? ")).lower()
two = str(input("“Esteve no local do crime? ")).lower()
three = str(input("Mora perto da vítima? ")).lower()
four = str(input("Devia para a vítima? ")).lower()
five = str(input("Já trabalhou com a vítima? ")).lower()
results = [one, two, three, four, five]
result = "Inocente"

if results.count("sim") == 2:
  result = "Suspeita"
elif results.count("sim") >= 3 and results.count("sim") <= 4:
  result = "Cúmplice"
elif results.count("sim") == 5:
  result = "Assasino"

print(result)

one = float(input("Valor do primeiro produto: "))
two = float(input("“Valor do segundo produto: "))
three = float(input("Valor do terceiro produto: "))
result = f"Melhor produto é o terceiro com o valor de {three}"

if one < two and one < three:
  result = f"Melhor produto é o primeiro com o valor de {three}"
elif two < one and two < three:
  result = f"Melhor produto é o primeiro com o valor de {three}"
elif one == two and one == three:
  result = "Produtos tem valores iguais"
1
print(result)

temperatura = str(input('digite cf se quer converter de celsus para fahrenheit ou fc de fahrenheit para celsus: ')).lower()
graus = float(input('digite a temperatura: '))

if temperatura == 'cf':
  print(graus*1.8+32)
elif temperatura == 'fc':
  print((graus-32)* 5/9)
else:
  print('invalido')
# F = C x 1,8 + 32.
#°C = (°F - 32) × 5/9