# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMYm5IkzzZkQte8-yE0hCx0WzKlUqsyW

Ler uma lista 5 números inteiros e mostre cada número juntamente com a sua posiçao na lista
"""

lista = list(range(5))

for idx in lista:
  print(f"{idx}: {lista[idx]}")

"""Ler uma lista de 10 números reais e mostre-os na ordem inversa que foram lidos"""

lista = list(range(10))

lista.reverse()
print(lista)

"""Ler uma lista com 5 idades e exibir a maior e a menor."""

lista = []

for i in range(5):
  lista.append(int(input("Digite uma idade ")))

print("\nMaior", max(lista), "\nMenor", min(lista))

"""Inicialize uma lista de 10 numeros inteiros. Armazene os numeros pares em uma lista PAR e os numeros impares em uma lista IMPAR. Imprima as listas PAR e IMPAR"""

lista = list(range(10))

listaPares = [n for n in lista if n % 2 == 0]

listaImpares = [n for n in lista if n % 2 != 0]

print("Pares", listaPares, "\n", "\nImpares:", listaImpares)

"""Escreva um programa que troque o primeiro com o último
elemento de uma lista qualquer.
"""

lista = list(range(10))

lista.insert(-len(lista), lista[-1])
lista[-1] = lista[-len(lista) + 1]
lista.pop(-len(lista) + 1)

print(lista)

"""Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.

produtos = {
'camiseta': (25.00, 10),
'calça': (45.00, 5),
'sapato': (60.00, 3),
'boné': (15.00, 8)
}

Você deve criar um programa em Python que solicite ao usuário que insira um preço
máximo. Em seguida, o programa deve imprimir os produtos cujo preço seja menor ou
igual ao preço máximo inserido pelo usuário.
"""

produtos = {
'camiseta': (25.00, 10),
'calça': (45.00, 5),
'sapato': (60.00, 3),
'boné': (15.00, 8)
}

maxPrice = float(input("Digite um preço máximo "))

result = []

for idx, val in produtos.items():
  if val[0] <= maxPrice:
    result.append((idx, produtos[idx]))

if len(result) > 0:
  print("\nProdutos:")
  for d in result:
    print(d[0],": R$", d[1][0])
else:
  print("Nenhum produto com menor preço foi encontrado")

"""Em uma competição de ginástica, cada atleta recebe votos de
sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica
sendo a média dos votos restantes. Você deve fazer um programa
que receba o nome do ginasta e as notas dos sete jurados
alcançadas pelo atleta em sua apresentação e depois informe a sua
média, conforme a descrição acima informada (retirar o melhor e o
pior salto e depois calcular a média com as notas restantes). As
notas não são informadas em ordem crescente ou decrescente.
"""

atleta = {}
atleta["nome"] = str(input("Informe o nome do atleta: "))
atleta["notas"] = []

for idx in range(7):
  nota = int(input("Nota do primeiro jurado: "))
  atleta["notas"].append(nota)

atleta["notas"].remove(min(atleta["notas"]))
atleta["notas"].remove(max(atleta["notas"]))

media = sum(atleta["notas"]) / len(atleta["notas"])
print("\nMédia =", media)